from flask import Flask

from American_Airlines.american_airlines import AmericanAirlines
from Delta_Airlines.delta_airlines import DeltaAirlines
from Southwest_Airlines.southwest_airlines import SouthwestAirlines
from United_Airlines.united_airlines import UnitedAirlines
